#:schema node_modules/wrangler/config-schema.json
name = "nvd-worker"
main = "src/index.ts"      # This points to your entry file
compatibility_date = "2024-11-06"

# Cron Triggers
[triggers]
crons = [
  "*/30 * * * *",  # Existing NVD Sync
  "0 0 */2 * *"    # New KEV Sync every 2 days
]

[[d1_databases]]
binding = "DB" 
database_name = "NVD_DB"
database_id = "b8ab57ef-7401-4395-a..." # Copy from your dashboard
